# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: WiraDeltaIndonesia.WiraDesk
PackageVersion: 0.3.0
InstallerType: inno
Scope: machine
InstallModes:
  - silent
  - silentWithProgress
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/wiradeltaid/wira-desk/releases/download/v0.3.0/WiraDesk-0.3.0-x64-setup.exe
    InstallerSha256: 7C968968F1B0B61F5B2D7C47A72A9F48BE23C9237DCE7AE02908B405664667DF
ManifestType: installer
ManifestVersion: 1.10.0
